Console.Beep(1700, 1000);
Console.WriteLine("Hi!");
await Task.Delay(1000);
//pressing a key to start
Console.Write("Press a ");
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.Write("Key");
Console.ResetColor();
Console.WriteLine("...");
Console.ReadKey(true);
//first beep
Console.Beep(600, 80);
Console.Beep(700, 80);
Console.Beep(1000, 200);
await Task.Delay(1700);
Console.Clear();
await Task.Delay(1000);
Console.ForegroundColor = ConsoleColor.DarkYellow;
Console.WriteLine("Good afternoon!");
await Task.Delay(1000);
Console.ResetColor();
//my name
Console.Write("My name is ");
Console.ForegroundColor = ConsoleColor.Green;
//beep with name
Console.Beep(900, 100);
Console.Beep(1000, 300);
Console.Write("Tootia! ");
Console.ResetColor();
await Task.Delay(1500);
Console.Write("Or i can say  ");
await Task.Delay(500);
//color
Console.ForegroundColor = ConsoleColor.Green;
//write T
Console.Beep(1200, 300);
Console.Write("-  ");
await Task.Delay(1500);
//write o
Console.Beep(1200, 300);
Console.Write("-");
Console.Beep(1200, 300);
Console.Write("-");
Console.Beep(1200, 300);
Console.Write("-  ");
await Task.Delay(1500);
//write o
Console.Beep(1200, 300);
Console.Write("-");
Console.Beep(1200, 300);
Console.Write("-");
Console.Beep(1200, 300);
Console.Write("-  ");
await Task.Delay(1500);
//write t
Console.Beep(1200, 300);
Console.Write("-  ");
await Task.Delay(1500);
//write i
Console.Beep(1200, 100);
Console.Write(".");
await Task.Delay(1000);
Console.Beep(1200, 100);
Console.Write(".  ");
await Task.Delay(1500);
//write a
Console.Beep(1200, 100);
Console.Write(".");
await Task.Delay(1000);
Console.Beep(1200, 300);
Console.WriteLine("-  ");
await Task.Delay(1000);
Console.ResetColor();
await Task.Delay(2000);
//my age
await Task.Delay(1000);
Console.Write("I'm ");
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Write("19. ");
Console.ResetColor();
await Task.Delay(1200);
//age in math
Console.Write("Or ");
//3!
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Beep(600, 400);
Console.Write("3!");
Console.ResetColor();
await Task.Delay(700);
//*
Console.ForegroundColor = ConsoleColor.Red;
Console.Beep(1200, 400);
Console.Write("*");
Console.ResetColor();
await Task.Delay(700);
//3
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Beep(600, 400);
Console.Write("3");
Console.ResetColor();
await Task.Delay(700);
//+
Console.ForegroundColor = ConsoleColor.Red;
Console.Beep(1200, 400);
Console.Write("+");
Console.ResetColor();
await Task.Delay(700);
//1^1943
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Beep(600, 400);
Console.Write("1");
Console.ResetColor();
await Task.Delay(700);
Console.ForegroundColor = ConsoleColor.Red;
Console.Beep(1200, 400);
Console.Write("^");
Console.ResetColor();
await Task.Delay(700);
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Beep(600, 400);
Console.Write("1943 ");
Console.ResetColor();
await Task.Delay(700);
//age
Console.Write("Or ");
await Task.Delay(700);
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Beep(1200, 400);
Console.Write("1");
await Task.Delay(700);
Console.Beep(1200, 400);
Console.Write("0");
await Task.Delay(700);
Console.Beep(1200, 400);
Console.Write("0");
await Task.Delay(700);
Console.Beep(1200, 400);
Console.Write("1");
await Task.Delay(700);
Console.Beep(1200, 400);
Console.WriteLine("1");
Console.ResetColor();
await Task.Delay(1500);
//my birth month
Console.Write("I'll be ");
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Write("20 ");
Console.ResetColor();
Console.WriteLine("in may.");
await Task.Delay(2000);
//education
Console.Write("I study ");
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write("Geomatics Engineering ");
Console.ResetColor();
Console.WriteLine("In university.");
Console.WriteLine(" ");
//art
await Task.Delay(1700);
Console.Write("I love painting. ");
await Task.Delay(900);
Console.WriteLine("Any kind of it.");
await Task.Delay(1000);
Console.WriteLine("painting with: ");
await Task.Delay(1000);
//paint
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.Beep(500, 100);
Console.WriteLine("Color Pencil!");
await Task.Delay(1000);
Console.Beep(600, 100);
Console.WriteLine("Oil color!");
await Task.Delay(1000);
Console.Beep(700, 100);
Console.WriteLine("Dark pencil!");
Console.ResetColor();
Console.WriteLine(" ");
//Enlish
await Task.Delay(2000);
Console.Write("My apologeis for write this in ");
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine("English.");
Console.ResetColor();
await Task.Delay(1200);
Console.WriteLine("Not to brag!");
await Task.Delay(1000);
Console.Write("I know a little English and i was like ");
await Task.Delay(1000);
Console.ForegroundColor = ConsoleColor.DarkBlue;
Console.Beep(1000, 100);
Console.Beep(1300, 300);
Console.WriteLine("\"Hey!Let's use this little knowledge.\"");
Console.ResetColor();
await Task.Delay(1200);
Console.Write("And i'm not really good at ");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("Finglish.");
Console.ResetColor();
Console.WriteLine(" ");
await Task.Delay(2000);
Console.WriteLine("Anyway!");
await Task.Delay(1500);
Console.WriteLine("About myself...");
await Task.Delay(1500);
//Movies
Console.Write("I have a strange taste in ");
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine("movies.");
Console.ResetColor();
await Task.Delay(1500);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("*");
Console.ResetColor();
Console.WriteLine("I like the one Tim Burton made!");
await Task.Delay(1300);
Console.Write("Like ");
await Task.Delay(1000);
Console.Beep(1200, 100);
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Write("Big fish, ");
Console.WriteLine("Miss peregrine's home for pecuilar children, etc");
Console.ResetColor();
await Task.Delay(1500);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("*");
Console.ResetColor();
Console.WriteLine("The one Johnny Depp played in.");
await Task.Delay(1300);
Console.Write("Like ");
await Task.Delay(1000);
Console.Beep(1200, 100);
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.WriteLine("Sleepy hallow, etc");
Console.ResetColor();
await Task.Delay(1500);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("*");
Console.ResetColor();
Console.WriteLine("The one about escaping reality.");
await Task.Delay(1300);
Console.Write("Like ");
await Task.Delay(1000);
Console.Beep(1200, 100);
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.WriteLine("Narnia, etc");
Console.ResetColor();
await Task.Delay(1500);
Console.ForegroundColor = ConsoleColor.Red;
Console.Write("*");
Console.ResetColor();
Console.WriteLine("Those weird, witchy things!");
await Task.Delay(1300);
Console.Write("Like ");
await Task.Delay(1000);
Console.Beep(1200, 100);
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.WriteLine("The craft, Practical magic, etc");
Console.ResetColor();
Console.WriteLine(" ");
await Task.Delay(2000);
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("Wait");
Console.ResetColor();
await Task.Delay(1000);
Console.WriteLine("Did i bore you?");
await Task.Delay(1000);
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("If not press a key!");
Console.ResetColor();
Console.ReadKey(true);
Console.Clear();
await Task.Delay(1200);
Console.Write("So i love ");
Console.ForegroundColor = ConsoleColor.DarkBlue;
Console.Beep(1000, 500);
Console.Write("animals.");
Console.ResetColor();
await Task.Delay(1000);
Console.Write("Except ");
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.Beep(1700, 500);
Console.WriteLine("birds!");
Console.ResetColor();
Console.WriteLine("I have this weird phobia of birds.");
await Task.Delay(1000);
Console.Beep(1700, 500);
Console.WriteLine("Their legs!");
Console.Write("And the way they move their ");
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.Beep(1700, 500);
Console.Write("wings ");
Console.ResetColor();
await Task.Delay(1000);
Console.Write("when they wanna ");
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.Beep(1700, 500);
Console.WriteLine("fly!");
Console.ResetColor();
await Task.Delay(1000);
Console.WriteLine("They absolutely freak me out!");
Console.WriteLine(" ");
//pet
await Task.Delay(1300);
Console.Write("I have a ");
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.WriteLine("pet.");
Console.ResetColor();
await Task.Delay(1300);
Console.Write("His name is ");
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine("Bunny");
Console.ResetColor();
await Task.Delay(1300);
Console.Write("As you can tell from his name, he's a ");
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.WriteLine("Rabit!");
Console.ResetColor();
await Task.Delay(1300);
Console.Write("He's ");
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.Write("7 ");
Console.ResetColor();
Console.WriteLine("years old.");
await Task.Delay(1300);
Console.Write(@"And the average lifespan of a healthy rabit is around ");
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.Write("8-9 ");
Console.ResetColor();
Console.WriteLine("years.");
await Task.Delay(1300);
Console.WriteLine(" ");
Console.Write("He's getting ");
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.Write("old ");
Console.ResetColor();
Console.WriteLine("now. I know!");
await Task.Delay(1300);
Console.WriteLine("He acts like it, too!");
await Task.Delay(1300);
Console.WriteLine("He sleep more these days.");
await Task.Delay(1300);
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine("No more jumping around, no more making a mess like he used to.");
Console.ResetColor();
await Task.Delay(1300);
Console.WriteLine("He mostly just rests and sleeps these days.");
await Task.Delay(1300);
Console.WriteLine("It's upsetting. So no more talking about him.");
await Task.Delay(1300);
Console.WriteLine(" ");
Console.Write("I have a ");
Console.ForegroundColor = ConsoleColor.DarkBlue;
Console.WriteLine("dream.");
Console.ResetColor();
await Task.Delay(1300);
Console.Write("I want to learn all the ");
Console.ForegroundColor = ConsoleColor.DarkBlue;
Console.Write("language ");
Console.ResetColor();
Console.WriteLine("in the world.");
await Task.Delay(1300);
Console.Write("I wanna be an ");
Console.ForegroundColor = ConsoleColor.DarkBlue;
Console.Write("artist");
Console.ResetColor();
Console.WriteLine(", Especially with ");
Console.ForegroundColor = ConsoleColor.DarkBlue;
Console.WriteLine("colored pencil.");
Console.ResetColor();
await Task.Delay(1300);
Console.WriteLine(" ");
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.WriteLine("Thank you for watching!");
Console.ResetColor();
await Task.Delay(1300);
Console.WriteLine(" ");
Console.ForegroundColor = ConsoleColor.DarkCyan;
Console.WriteLine("Tootia:)");
Console.ResetColor();
//end